export const PERMISSION_REPOSITORY = Symbol('PERMISSION_REPOSITORY');
export const ROLE_REPOSITORY = Symbol('ROLE_REPOSITORY');
export const PRINCIPAL_ROLE_REPOSITORY = Symbol('PRINCIPAL_ROLE_REPOSITORY');
