export const USER_REPOSITORY = Symbol(
    'USER_REPOSITORY',
);

export const CREDENTIAL_REPOSITORY = Symbol(
    'CREDENTIAL_REPOSITORY',
);

export const REFRESH_TOKEN_REPOSITORY = Symbol(
    'REFRESH_TOKEN_REPOSITORY',
);