# ==============================================================================
# ARGO CD GITOPS DECLARATIVE APPLICATION MANIFEST
# ==============================================================================
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: atlas-hrm-production
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  # Nguồn Chân Lý Duy Nhất (Single Source of Truth - Git Repo)
  source:
    repoURL: 'https://github.com/TuanStark/Atlas-Enterprise-Platform.git'
    targetRevision: main
    path: charts/atlas-hrm
    helm:
      valueFiles:
        - values-prod.yaml

  # Đích đến triển khai trên Kubernetes Cluster
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: hrm-system

  # Chính sách Tự động Đồng bộ (Automated GitOps Sync Policy)
  syncPolicy:
    automated:
      prune: true       # Tự động xóa tài nguyên trên K8s nếu đã bị xóa khỏi Git
      selfHeal: true    # Tự động Revert tài nguyên trên K8s nếu ai đó tự ý sửa tay
    syncOptions:
      - CreateNamespace=true
