# ==============================================================================
# SERVICE ACCOUNT (Identity & RBAC)
# ==============================================================================
{{- if .Values.serviceAccount.create }}

# [BẢN CHẤT - Danh tính của Máy Móc (Machine Identity)]
# K8s có 2 loại User: 1 là Người Thật (Nhân viên), 2 là Máy móc/Ứng dụng (ServiceAccount).
# 🚩 Lỗi Junior: Mặc định lười biếng để mọi Pod dùng chung 1 cái thẻ tên là "default". Nếu lỡ gán quyền cho thẻ "default" này (vd: quyền Xóa Pod), thì 1 Pod bị hack sẽ giúp hacker đi tàn sát cả cụm.
# 🟩 Senior Review: Áp dụng nguyên tắc Đặc Quyền Tối Thiểu (Least Privilege). Mỗi ứng dụng (Frontend, Backend) phải có 1 thẻ nhân viên (ServiceAccount) của riêng nó. Không xài chung.

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "atlas-hrm.serviceAccountName" . }}
  namespace: {{ include "atlas-hrm.namespace" . }}
  labels:
    {{- include "atlas-hrm.labels" . | nindent 4 }}
  annotations:
    # [BẢN CHẤT - Tích hợp Cloud IAM (AWS IRSA / GCP Workload Identity)]
    # Nếu Backend cần upload file lên AWS S3, tuyệt đối KHÔNG lưu AWS_ACCESS_KEY vào Secret (Rất dễ lộ).
    # Ta cấu hình AWS tin tưởng K8s. Sau đó gắn số thẻ định danh ARN của AWS IAM Role vào annotation này. AWS sẽ tự động cấp phát token rác xoay vòng liên tục cho Pod. An toàn tuyệt đối.
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    
# [BẢN CHẤT - Tước quyền K8s API]
# Theo mặc định K8s luôn nhét 1 cái thẻ API Token vào trong lòng Container để nó giao tiếp với bộ não K8s.
# 🟩 Senior Review: Trừ khi app của bạn là tool giám sát hạ tầng, còn app Web bình thường thì KHÔNG BAO GIỜ cần gọi lệnh xuống K8s. Tắt nó đi (automount: false) để giảm thiểu bề mặt tấn công.
automountServiceAccountToken: {{ .Values.serviceAccount.automountToken }}
{{- end }}
